name: CI Extension tests
on: [push]
jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.36.2-focal
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build bundle
        run: npm run build

      # - name : Build vite app
      #   run: cd test-extension/dapp-vite && npm i && npm run build 

      - name: Test using dummy extension
        run: HOME=/root npm run test-extension
