name: Npm nightly publish

on:
  push:
    branches: [ main ]

jobs:
  publish-npm-dev:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
        
      - name: publish dev version to npm
        run: ./scripts/publish-dev.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
